# importing nupmy

In [2]:
import numpy as np

# creating an array using array

In [3]:
x=np.array([])

In [4]:
type(x)

numpy.ndarray

In [6]:
# ndarray means n-dimentional array

In [7]:
p=np.array([4,6,2,8,12,2,7])
p

array([ 4,  6,  2,  8, 12,  2,  7])

In [8]:
type(x)

numpy.ndarray

In [9]:
p.ndim  # shows dimention of an array

1

# indexing and slicing of an array 

In [10]:
p[4]

12

In [11]:
p[-1]

7

In [12]:
p[6]

7

# slicing

In [13]:
p[2:5]

array([ 2,  8, 12])

In [14]:
p

array([ 4,  6,  2,  8, 12,  2,  7])

In [15]:
p[4:]

array([12,  2,  7])

In [16]:
p[4:7]

array([12,  2,  7])

In [17]:
p[-3:]  #prints last value of an array

array([12,  2,  7])

# differences between array and the list
* lists supports multiple datatype; however, array supports homogeneous datatype.
* array are faster than list
* array are memory-efficient than list

In [20]:
list_1=[True,60.5,6, "hello"]
type(list_1[0])

bool

In [19]:
list_1

[True, 60.5, 6, 'hello']